### PR TITLE
Attempt to revive exceptions

### PR DESCRIPTION
**Pull request by leotsarev**
Should I continue thus attempts? :-)

- [ ] Revive tests
- [ ] Add VSIX (is this required? Could be done in separate PR?)

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
> Should I continue thus attempts? :-)

Absolutely!

**Comment by leotsarev** [comment]
Current version correctly compiles to Nuget and could be installed into my project.
Could you please check this and publish nuget package?
Could tests and VSIX be moved to separate issues?

**Comment by SergeyTeplyakov** [comment]
I'm on vacation right now (that's the reason why it took soo long to approve these useful changes).
I'll publish the new version with a few bug fixes in a day or two.

Thanks for your amazing contributions!

**Comment by leotsarev** [comment]
It's just reviving your code. I'll hope that I'll have capacity to actually contribute meaningful changes later.

**Pull request merged**
