### PR TITLE
Attempt to move to nuget build

### LINKED ISSUE #12: Not clear how to install and execute ErrorProne.NET on user's c# solution

### PR DESCRIPTION
**Pull request by leotsarev**
fixes #12 
Sad consequences: 
 - ILMerge
 - ILMerge w/o PDB
 - Moving to .net framework (cause ILMerge doesn't support Core yet)

### CODE REVIEW

**Comment by leotsarev** [comment]
After thought: is means cutting of Linux/MacOS developers. It's not ok, probably
However, my google-fu still fails to found better solution. M.b. investigate futher

**Comment by leotsarev** [comment]
To myself: tryehttps://github.com/gluck/il-repack

**Comment by SergeyTeplyakov** [comment]
@leotsarev I've noticed that nuget has some issues with project-to-project references, but I don't think switching to .net build is a good solution:(

So I've tried something simple, and here what I did: https://github.com/SergeyTeplyakov/ErrorProne.NET/pull/50

Is there anything completely wrong with my solution?

If my solution is not ok, then maybe other tricks would be good, like ones that described here: https://github.com/dotnet/cli/issues/3959

**Comment by leotsarev** [comment]
I'm closing this.
@SergeyTeplyakov I think now that's possible for your to setup public Nuget for ErrorProne.Net.Exceptions. isn't it?

**Pull request closed without merging**
