### PR TITLE
Updates from Progressive Insurance fork of Error Prone.net Closes #246 Closes #209 Closes #251 Closes #236 Closes #232 Closes #231 Closes #216 Closes #260

### LINKED ISSUE #209: False positive on ERP022 Exit point '}' swallows an unobserved exception
The following method incorrectly throws Warning ERP022 Exit point '}' swallows an unobserved exception.". The variable `exception` is put into an anonymous type.

```
    public List<T> LoadList<T>(string key, string subKey = "") {
      try {
      } catch (Exception exception) {
        Logger.Fatal?.Add($"{new { key, subKey, exception }}");
      }
    }
```

### LINKED ISSUE #216: [TechnicalDebt] Update roslyn SDK

### LINKED ISSUE #231: Unify package versions in 'packages.config'

### LINKED ISSUE #232: Stop using 'Microsoft.CodeAnalysis.FxCopAnalyzers' use .net sdk analyzers instead

### LINKED ISSUE #236: Update to the latest 'Microsoft.CodeAnalysis' packages

### LINKED ISSUE #246: EPC12 creates diagnostic with description "bar"
Version: 0.1.2 and 0.4.0-beta.1 alike

When only observing the Message property of an exception, VS shows a strange message "bar" from EPC12:
image

This can even show up in the error list:
image

Also note that in the first screenshot, we get two diagnostics. The second one references a non-existing line number 22.

Could this be some foo/bar/baz code left behind somewhere? I already searched for "bar" in this repo and the roslyn and roslyn-analyzer repos, but could not find any plausible usages.

### LINKED ISSUE #251: The committed src/global.json is invalid.
At current HEAD of master, it's this (literally):

```
{
  "sdk": {
<<<<<<< Updated upstream
    "version": "3.1.200"
=======
    "version": "5.0.202"
>>>>>>> Stashed changes
  }
}
```

Which version should it be?

### LINKED ISSUE #260: Readme appears incomplete and hard to trace Documentation, Messages and Codes
For the ErrorProne.Net.CoreAnalyzers, the readme describes about 4 different rules. When installing and running the analyzer it shows 12 different Codes. 

There should be one section for each Code/Message or at least a mapping that makes it easy to align them to the related documentation. 

1. ERP031
2. EPC13
3. EPC12,EPC12WithoutSuggestion
4. EPC18
5. EPC11,EPC11WithoutSuggestion
6. ERP022
7. EPC19
8. EPC17
9. ERP021
10. EPC15,EPC15WithoutSuggestion
11. EPC14,EPC14WithoutSuggestion
12. EPC16

### PR DESCRIPTION
**Pull request by mkerkelpgr**
* Update dependencies

* Issue #209 and anonymous usage EPC12 and ERP022

* Fix Traget framework for test projects

* Fix Issue 251 The committed src/global.json is invalid.

* Issue #260 Added som error codes to examples for the error related warnings.

### CODE REVIEW

**Comment by mkerkelpgr** [comment]
Closes #246 Closes #209 Closes #251 Closes #236 Closes #232 Closes #231 Closes #216 Closes #260

**Comment by SergeyTeplyakov** [comment]
LGTM. Thanks for the contributions!

**Comment by SergeyTeplyakov** [comment]
I'll publish a new version later this week.

**Comment by mkerkelpgr** [comment]
Thanks so much.

From: Sergey Teplyakov ***@***.***>
Sent: Thursday, November 16, 2023 1:09 PM
To: SergeyTeplyakov/ErrorProne.NET ***@***.***>
Cc: Michael Kerkel ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [SergeyTeplyakov/ErrorProne.NET] Updates from Progressive Insurance fork of Error Prone.net Closes #246 Closes #209 Closes #251 Closes #236 Closes #232 Closes #231 Closes #216 Closes #260 (PR #261)


Merged #261<https://github.com/SergeyTeplyakov/ErrorProne.NET/pull/261> into master.

**Pull request merged**
